### PR TITLE
add Dockerfile.rhel7 for OpenShift build

### PR DESCRIPTION
**Pull request by zshi-redhat**

### CODE REVIEW

**Comment by zshi-redhat** [comment]
@ahalim-intel @przemeklal PTAL

**Comment by przemeklal** [comment]
lgtm

**Comment by ahalim-intel** [comment]
@przemeklal I have one comment, not about this PR but related. 
I see, existing Dockerfile is under `build/` directory. Maybe we should consolidate all docker files in same location.

**Comment by przemeklal** [comment]
in most of our projects we keep in the top level so I moved it there as well, please see PR #3

**Pull request merged**
